[profile.default]
src = "src"
out = "out"
libs = ["lib"]
ast = true

[fmt]
multiline_func_header = "params_first"
number_underscore = "thousands"
single_line_statement_blocks = "single"
sort_imports = true
wrap_comments = true
